name: Train Model on Azure ML

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install Azure ML CLI v2
      run: |
        pip install azure-ai-ml azure-identity
        az extension add -n ml -y

    - name: Submit training job
      run: |
        az ml job create --file src/training-job.yml --resource-group ${{ secrets.AZURE_RG }} --workspace-name ${{ secrets.AZURE_WS }}
